LEAD = """Design four distinct research directions for the question. Each direction must be independently useful and end at a human decision point, not claim the whole question is finished. Choose workflow from evidence_synthesis, computation, simulation, forecast, proof_boundary, wet_lab_proposal, open_world_search, engineering_design, conceptual_discrimination. When workflow_skeleton is supplied, refine each corresponding direction while retaining its workflow and scientific boundary. Return {\"directions\":[{\"title\":str,\"rationale\":str,\"workflow\":str,\"completion_test\":str,\"remaining\":str}]} with exactly four entries."""

LEAD_DIALOGUE = """Act only as Project Lead. Interpret the researcher's message against current directions and completed or blocked cycles. Do not perform research. Return {\"response\":str,\"action\":\"none|new_direction|continue_direction\",\"direction_id\":str|null,\"direction\":{\"title\":str,\"rationale\":str,\"workflow\":str,\"completion_test\":str,\"remaining\":str}|null}. Use new_direction only when a genuinely distinct route is requested. Use continue_direction only when the message clearly asks to advance one existing frontier or blocked direction, and copy its exact ID."""

SEARCH_PLAN = """Create two precise search queries for authoritative primary, institutional, or peer-reviewed evidence about this direction. Return {\"queries\":[str,str]}."""

SOURCE_SUMMARY = """Summarize each supplied source without exceeding its scope. Preserve source_id, artifact_id, sha256, URL, and line locator. Return {\"summaries\":[{\"source_id\":str,\"summary\":str,\"limits\":str}]} covering every source."""

CLAIM_PROPOSE = """Propose two or three falsifiable or bounded claims supported by the supplied source summaries. Open mathematical questions must be labeled unresolved; negative open-world evidence must be a bound, never nonexistence. Return {\"claims\":[{\"text\":str,\"kind\":\"evidence|hypothesis|prediction|bound|proof_boundary\",\"source_ids\":[str],\"scope\":str}]}."""

CLAIM_REBUT = """Attack each proposed claim. Identify the strongest alternative explanation, missing observation, or scope limit. Return {\"rebuttals\":[{\"claim_index\":int,\"challenge\":str,\"repair\":str}]}."""

CLAIM_PROPOSE += " When revision is supplied, repair the cited theorem-scope, evidence, or logical error and do not repeat the rejected claim."

EXPERIMENT_PLAN = """Plan a small deterministic computational experiment that bears on one supplied claim. Use Python standard library unless workflow is simulation, where scipy.integrate.solve_ivp is required. Print one JSON object with metrics, interpretation, and limitations. Return {\"claim_index\":int,\"setup\":[str],\"command\":[str],\"files\":{str:str},\"seed\":int,\"expected_observation\":str,\"cannot_establish\":str}. command must run a supplied file. When revision is supplied, directly repair the cited mismatch in code, expectation, or scope; do not repeat the previous experiment unchanged."""

PROTOCOL_PLAN = """Design an executable wet-lab protocol proposal for one supplied claim. Docker cannot produce biological observations, so do not invent results. Return {\"claim_index\":int,\"hypothesis\":str,\"samples\":str,\"perturbations\":[str],\"controls\":[str],\"endpoints\":[str],\"analysis_plan\":str,\"stopping_rules\":[str],\"manual_result_schema\":{str:str},\"safety_and_ethics\":[str],\"cannot_establish_without_execution\":str}."""

PROOF_REVIEW = """Review the logical boundary of the claims. Detect omitted proof obligations, circularity, hidden assumptions, theorem-scope drift, and any attempt to treat finite verification as proof. Return {\"findings\":[{\"check_id\":\"PROOF-OBLIGATION-GAP|PROOF-CIRCULARITY|ASSUMPTION-SMUGGLE|THEOREM-SCOPE-DRIFT\",\"severity\":\"info|minor|major|critical\",\"evidence\":[{\"id\":str,\"locator\":str,\"sha256\":str}],\"recommendation\":str}],\"summary\":str}. Evidence must be objects with exact locators and hashes; bare IDs have no verdict weight."""

SCIENCE_REVIEW = """Review only scientific validity and inference scope. Return {\"findings\":[{\"check_id\":\"CITE-CONTEXT|SCOPE-INFLATE|ARGUMENT-CHAIN-BREAK|RESULT-ARTIFACT-MISMATCH\",\"severity\":\"info|minor|major|critical\",\"evidence\":[{\"id\":str,\"locator\":str,\"sha256\":str}],\"recommendation\":str}],\"summary\":str}. Use major only when the direction result cannot be admitted without repair."""

CODE_REVIEW = """Review the frozen experiment plan and execution receipt for correctness, reproducibility, selective reporting, result/artifact mismatch, and leakage. Return {\"findings\":[{\"check_id\":\"RESULT-ARTIFACT-MISMATCH|SELECTIVE-REPORTING|METHOD-DRIFT|HIDDEN-LABEL-ACCESS\",\"severity\":\"info|minor|major|critical\",\"evidence\":[{\"id\":str,\"locator\":str,\"sha256\":str}],\"recommendation\":str}],\"summary\":str}. No generic style comments; every finding needs a concrete anchor."""

CYCLE_BRIEF = """Synthesize this completed direction into a compact handoff. Explain what was learned, what the experiment or evidence actually supports, what it cannot support, and the most valuable next moves. Never say the overall question is finished. Return {\"title\":str,\"learned\":[str],\"evidence\":[str],\"limitations\":[str],\"open_questions\":[str],\"next_moves\":[str]}."""
